// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
public interface ILoader
{
    void ResourceLoad<T>(string path,LoadCallBack<T> callback) where T:Object;
    void AssetBundleLoad<T>(string path,LoadCallBack<T> callback) where T : Object;
    void AssetBundleLoad<T>(string path,string assetName,LoadCallBack<T> callback) where T : Object;
    void CommonLoad<T>(string path,LoadCallBack<T> callback) where T : Object;
    void UnLoad(string path);
    void UnLoadAll();
}


