// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;

public delegate void LoadCallBack<T>(T param);

public abstract class LoaderData
{
    public abstract void StartLoad();
}

public class LoaderData<T> : LoaderData where T : Object{
    private string Path;
    private LoadCallBack<T> Callback;
    private bool IsBundle;

    public LoaderData(string path,LoadCallBack<T> callback,bool isBundle = false){
        Path = path;
        Callback = callback;
        IsBundle = isBundle;
    }

    public override void StartLoad()
    {
        if(IsBundle){

        }else{

        }
    }
}

