// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
public class ComponentBase<T> : MonoBehaviour where T : Inventory, new ()
{
    protected T data;
    public T Data{
        get{
            return data;
        }
        set{
            data = value;
            Reset();
        }
    }
    public virtual void Reset(){

    }

}

