// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;


public class CoroutineInstance : MonoBehaviour
{
    public static Coroutine InitCoroutine(IEnumerator routine){
        return InitCoroutine(routine,"Coroutine",false);
    }
    public static Coroutine InitCoroutine(IEnumerator routine,string routineName){
        return InitCoroutine(routine,"Coroutine-" + routineName,false);
    }
    public static Coroutine InitCoroutine(IEnumerator routine,string routineName,bool dontDestroyOnLoas){
        GameObject routineHandlerObject = new GameObject(routineName);
        CoroutineInstance routineHandler = routineHandlerObject.AddComponent<CoroutineInstance>();
        if(dontDestroyOnLoas){
            GameObject.DontDestroyOnLoad(routineHandlerObject.gameObject);
        }
        return routineHandler.ProcessWork(routine);
    }

    private Coroutine ProcessWork(IEnumerator routine){
        return StartCoroutine(DestroyWhenComplete(routine));
    }
    private IEnumerator DestroyWhenComplete(IEnumerator routine){
        yield return StartCoroutine(routine);
        Destroy(gameObject);
    }
}

